pipeline {
    agent any
    parameters {
        string(name:'COMPONENT',defaultValue:'catalogue')
        booleanParam(name:'TOGGLE',defaultValue:true)
        choice(name:'CHOICE',choices:['Dev','Test','Prod'],description:'pick something')
        text defaultValue: 'Joe', name: 'PERSON'
    }
    stages{
        stage('parameters') {
            steps {
                echo "Component is ${params.COMPONENT}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Name ${params.PERSON}"
            }
        }
    }
    post {
        success {
            echo "${params.COMPONENT} component pipeline is success"
        }
    }
}