- name: Variables
  hosts: localhost
  tasks:
    - name: defining variables task level
      vars:
        role: "DevOps Engineer"
        exp: "8 years"
      ansible.builtin.debug:
        msg: "I am working as a {{role}} and having {{exp}} of experience"