- name: Ansible condition
  hosts: localhost
  tasks:
  - name: create user
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true
  - name: Print variable value
    ansible.builtin.debug:
      msg: "user output is {{user}}"
  - name: Print return code
    ansible.builtin.debug:
      msg: "{{user.rc}}"
