- name: Catalogue configuration
  hosts: catalogue
  tasks:
  - name: Disable nodejs
    ansible.builtin.package:
      name: nodejs
      state: absent
  - name: Install nodejs version 18
    ansible.builtin.package:
      name: "@nodejs:18"
      state: present
  - name: Create user
    ansible.builtin.user:
      name: roboshop
  - name: Create directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: Archive application code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: Install dependencies
    # ansible.builtin.command:
    #   name: npm
    #   state: present
    #   args:
    #     chdir: /app 
    npm:
      path: /app
  - name: Copy catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: daemon reload catalogue service
    ansible.builtin.systemd_service:
      daemon_reload: yes
      enabled: yes
      state: started
  - name: mongodb client copy
    ansible.builtin.copy:
      src: mongodb.repo
      path: /etc/yum.repos.d/mongodb.repo
  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  - name: Load schema
    