- name: Dispatch install and Configuration
  hosts: dispatch
  become: yes
  vars_prompt:
    - name: RABBITMQ_HOST
      prompt: Enter rabbitmq domani name/IP
      private: false
  tasks:
  - name: Install golang
    ansible.builtin.package:
      name: golang
      state: present
  - name: create user for application
    ansible.builtin.user:
      name: roboshop
  - name: Create directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download application src
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp
  - name: Unarchive application src
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
  - name: Install dependencies and build applicaion
    ansible.builtin.package:
      name: "{{ item }}"
      args:
        chdir: /app
      loop:
      - go mod init dispatch
      - go get
      - go built
  - name: Copy dispatch.service file
    ansible.builtin.systemd_service:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service
  - name: Copy domain name/IP 
    ansible.builtin.replace:
      path: /etc/systemd/system/dispatch.service
      regexp: '<RABBITMQ-IPADDRESS>'
      replace: '{{ RABBITMQ_HOST }}'
  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon-reload: yes
  - name: Enable and Start dispatch service
    ansible.builtin.systemd_service:
      name: dispatch
      enabled: yes
      state: restarted